import Head from "next/head";
import localFont from "next/font/local";
import styles from "../styles/Home.module.css";
import CarouselCards from "components/CarouselCards";
import Fatest from "components/Fatest";
import { useEffect } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  useEffect(() => {
    // Telegram WebApp to'liq ekranda ochilishi uchun
    if (typeof window !== "undefined" && window.Telegram?.WebApp) {
      window.Telegram.WebApp.ready();
      window.Telegram.WebApp.expand();
    }

    // Sahifa 100% height bo'lishini ta'minlash
    document.documentElement.style.height = "100%";
    document.body.style.height = "100%";
    document.body.style.margin = "0";
    document.body.style.padding = "0";

    // Telegram WebApp orqali kirish holati uchun CSS o'zgartirishlar
    const mainElement = document.getElementById("mainContainer");
    if (mainElement) {
      mainElement.style.minHeight = "100vh";
      mainElement.style.display = "flex";
      mainElement.style.flexDirection = "column";
    }
  }, []);

  return (
    <>
      <Head>
        <title>NATION FOOD</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        id="mainContainer"
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
        style={{
          height: "100vh",
          overflow: "hidden",
          display: "flex",
          flexDirection: "column",
        }}
      >
        <CarouselCards />
        <Fatest />
      </div>
    </>
  );
}
